### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by preston176**
Added readme file

### CODE REVIEW

**Comment by shadrack-kimaau** [comment]
Nice piece

**Comment by shadrack-kimaau** [comment]
but check the code,. I tried to code what we are planning to do as our project. just simple denotion of it and put the repo as sth different to avoid catching eyes of many thinking is sth good though it was just a practice

**Comment by preston176** [comment]
ooh okay no problem

**Comment by shadrack-kimaau** [comment]
umeona?

**Pull request closed without merging**
